### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
import numpy as np
arr = np.random.randint(1,51, size=10)
mean_value = np.mean(arr)
std_value = np.std(arr)

print("Array: ", arr)
print("Média: ", mean_value)
print("Desvio padrão: ", std_value)



Array:  [29  3  6  4 21 11 29  7 37 18]
Média:  16.5
Desvio padrão:  11.508692367076288


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
import numpy as np
arr = np.random.rand(10)
arr[arr <= 0.5] = np.sqrt(arr[arr <= 0.5])
print (arr)

[0.29606901 0.61993833 0.38928542 0.8927449  0.27154327 0.81905424
 0.64720003 0.37638785 0.58281824 0.93242808]


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
import numpy as np
matriz_3d = np.random.rand(3, 3, 3)
max_values = np.amax(matriz_3d, axis=1)
print("Matriz 3D:\n", matriz_3d)
print("Valores máximos de cada linha de cada matriz 2D:\n", max_values)

Matriz 3D:
 [[[0.57277183 0.66900257 0.64673587]
  [0.35009511 0.86669681 0.11356011]
  [0.53361002 0.92315533 0.20288212]]

 [[0.49361545 0.73783449 0.58918949]
  [0.81724525 0.33559646 0.9868059 ]
  [0.16514517 0.93996083 0.41186074]]

 [[0.00842121 0.90634491 0.54244777]
  [0.72785328 0.87596955 0.61624925]
  [0.42944258 0.26560906 0.97116831]]]
Valores máximos de cada linha de cada matriz 2D:
 [[0.57277183 0.92315533 0.64673587]
 [0.81724525 0.93996083 0.9868059 ]
 [0.72785328 0.90634491 0.97116831]]


### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
import numpy as np
matriz = np.random.rand(5, 5)
media = np.mean(matriz, axis=1)
matriz_linha_media = matriz - media[:, np.newaxis]
print("Matriz original:\n", matriz)
print("Média de cada linha:\n", media)
print("Matriz com a média de cada linha subtraída:\n", matriz_linha_media)

Matriz original:
 [[0.61172112 0.90232552 0.28636919 0.13242189 0.48230119]
 [0.86439107 0.96957935 0.29238761 0.66556326 0.70289271]
 [0.9517469  0.85211162 0.6846626  0.31416111 0.84910405]
 [0.88704167 0.85391687 0.19002644 0.64911805 0.390624  ]
 [0.12097525 0.58724909 0.97598786 0.0146752  0.71190989]]
Média de cada linha:
 [0.48302779 0.6989628  0.73035726 0.5941454  0.48215946]
Matriz com a média de cada linha subtraída:
 [[ 0.12869334  0.41929774 -0.19665859 -0.35060589 -0.00072659]
 [ 0.16542827  0.27061655 -0.40657519 -0.03339954  0.00392991]
 [ 0.22138965  0.12175436 -0.04569466 -0.41619615  0.1187468 ]
 [ 0.29289627  0.25977146 -0.40411896  0.05497264 -0.20352141]
 [-0.36118421  0.10508963  0.4938284  -0.46748425  0.22975043]]


### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
import numpy as np
matriz = np.random.rand(4, 4)
diag_principal = np.diag(matriz)
diag_secundaria = np.diag(np.fliplr(matriz))
media_diag = np.mean([diag_principal, diag_secundaria])
std_diag = np.std([diag_principal, diag_secundaria])
print("Matriz:\n", matriz)
print("Diagonal principal:\n", diag_principal)
print("Diagonal secundária:\n", diag_secundaria)
print("Média das diagonais:", media_diag)
print("Desvio padrão das diagonais:", std_diag)


Matriz:
 [[0.4472587  0.36624119 0.45824945 0.75049037]
 [0.00691631 0.75568168 0.88962373 0.43521731]
 [0.84073286 0.13937234 0.6931889  0.11300497]
 [0.23030823 0.05511298 0.23297585 0.56648264]]
Diagonal principal:
 [0.4472587  0.75568168 0.6931889  0.56648264]
Diagonal secundária:
 [0.75049037 0.88962373 0.13937234 0.23030823]
Média das diagonais: 0.5590508236677757
Desvio padrão das diagonais: 0.24983461987717548
